### ISSUE TITLE
Add PI Institution to the Project Dashboard- Miriam August 6th

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/Data-Partnership-and-Governance#14]
Governance group asked if the PI Institution could be added to the project dashboard. 

I don't know how to add this ticket to the other testing tix issues and assign it to Miriam. @andrewjneumann @cgcook

**Comment by cgcook** [comment]
label added, ticket now in [enclave user testing project board](https://github.com/orgs/National-COVID-Cohort-Collaborative/projects/4)

**Comment by deacyma** [comment]
![image](https://user-images.githubusercontent.com/22172108/90827864-01a5a600-e30b-11ea-98eb-1aefe005c9be.png)
